---
title: Future and Odds
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
subtitle: by Ami-AZ
description: FO Repository
author: Ami-AZ
email: aminazmi10@gmail.com
avatar: assets/images/slowrushcurrent.jpg
baseurl: ''
url: https://ami-az.github.io
twitter_url: https://raw.githubusercontent.com/ami-az/ami-az.github.io/master/assets/images/omgpinguhijau.gif
facebook_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
github_url: 
pinterest_url: 
slack_url: 
dribbble_url: 
google_analytics: 
remote_theme: chrisbobbe/jekyll-theme-prologue
